---
title: "Bayesian Workflow book: Case studies"
date: 2026-02-26
date-modified: today
date-format: iso
format:
  html:
    number-sections: false
---

## Introduction

The code and data are provided to fully reproduce the examples and
figures in the book.  They can be a good way to see what the code
does. Different people have different styles of code and we don't
claim our style is the best.

When running the notebooks, to avoid the need to switch the working
directory, the `rprojroot` package is used to set the project root
directory. The downloaded git repository can be placed anywhere you
like and you can rename the Bayesian-Workflow directory if you
wish. When running the code, it is sufficient that the working
directory is any directory in the Bayesian-Workflow (or
renamed). Running
```
library("rprojroot")
root<-has_file(".Bayesian-Workflow-root")$make_fix_file()
```
will find the file `.Bayesian-Workflow-root` which is in the `Bayesian-Workflow` directory, 
and will set the full path according to that. Then, for example,
```
bioassay_stan_file <- root("bioassay","bioassay0.stan")
```
finds the `bioassay0.stan` file, no matter where you have placed or renamed the `Bayesian-Workflow` directory. When you switch to another example, there is no need to switch the working directory.

### Python case studies

There are also [Python versions of the case studies by Osvaldo Martin](https://arviz-devs.github.io/bayesian-workflow/)

## Case studies

- [Sec 3.5: Bioassay](bioassay/bioassay.html)
- [Ch 4: Modeling performance on a multiple choice exam](multiple_choice/multiple_choice.html)
- [Sec 9.4: Model selection using predictive performance](loo_comparison/loo_comparison.html)
- [Sec 11.4-6: How many iterations to run and how many digits to report](digits/digits.html)
- [Sec 12.3: Illustration of problematic posteriors](problems/problems.html)
- [Sec 12.4: Declining exponentials](declining_exponentials/declining_exponentials.html)
- [Ch 16: Coding a series of models: Simulated data of movie ratings](movies/movies.html)
- [Ch 17: Prior specification for regression models: Reanalysis of a sleep study](sleep_study/sleep_study.html)
- [Ch 18: Predictive model checking and comparison: Clinical trial](nabiximols/nabiximols.html)
- [Ch 19: Building up to a hierarchical model: Coronavirus testing](coronavirus/coronavirus.html)
- [Ch 20: Using a fitted model for decision analysis: Mixture model for time series competition](timeseries/timeseries.html)
- [Ch 21: Posterior predictive checking: Stochastic learning in dogs -- brms version](dogs/dogs.html)
- [Ch 21: Posterior predictive checking: Stochastic learning in dogs -- Stan version](dogs/dogs_stan.html)
- [Ch 22: Incremental development and testing: Black cat adoptions](cat_adoptions/cat_adoptions.html)
- [Ch 23: Debugging a model: World Cup football](world_cup/world_cup.html)
- [Ch 24: Leave-one-out cross validation model checking and comparison: Roaches](roaches/roaches.html)
- [Ch 25: Model building and expansion: Golf putting](golf/golf.html)
- [Ch 26: Model building with latent variables: Markov models for animal movement](sharks/sharks.html)
- [Ch 27: Model building: Time-series decomposition for birthdays](birthdays/birthdays.html)
- [Ch 28: Models for regression coefficients and variable selection: Student grades](variable_selection/variable_selection.html)
- [Ch 29: Sampling problems with latent variables: No vehicles in the park](park_rule/park_rule_aki.html)
- [Ch 30: Challenge of multimodality: Differential equation for planetary motion](planetary_motion/planetary_motion.html)
- [Ch 31: Simulation-based calibration checking in model development workflow](sbc/sbc.html)

## Software versions

We list here all the software packages used in the case studies and the versions used
when rendering the case study web pages 2026-06-26.

```{r, echo=FALSE}
# Extract package names from R files
get_pkgs <- function(file) {
  code <- paste(gsub("#.*$", "", readLines(file, warn = FALSE)), collapse = "\n")
  lib_pat <- "\\b(library|require)\\s*\\(\\s*['\"]?([A-Za-z0-9.]+)"
  col_pat <- "\\b([A-Za-z0-9.]+):::"
  c(gsub(lib_pat, "\\2", regmatches(code, gregexpr(lib_pat, code))[[1]]),
    gsub(col_pat, "\\1", regmatches(code, gregexpr(col_pat, code))[[1]])) |> unique()
}

# Get first sentence of description
first_sentence <- function(pkg) {
  if (pkg == "CmdStan") return("The command-line interface to Stan.")
  desc <- tryCatch(packageDescription(pkg), error = function(e) NULL)
  if (is.null(desc) || !is.list(desc) || is.null(desc$Description)) return("")
  txt <- trimws(gsub("\\s+", " ", desc$Description))
  for (i in seq_len(nchar(txt))) {
    if (substr(txt, i, i) %in% c(".", "?", "!")) {
      before <- substr(txt, 1, i - 1)
      if (grepl("\\) ?$", before)) return(substr(txt, 1, i))
      if (grepl("[. ][A-Za-z]$", before)) next
      if (grepl("[A-Za-z]{2,}$", before)) return(substr(txt, 1, i))
    }
  }
  txt
}

# Get package URL
get_url <- function(pkg) {
  special <- c(brms = "https://paulbuerkner.com/brms/",
               CmdStan = "https://mc-stan.org/cmdstanr/",
               priorsense = "https://n-kall.github.io/priorsense/")
  if (pkg %in% names(special)) return(special[[pkg]])
  desc <- tryCatch(packageDescription(pkg), error = function(e) NULL)
  if (!is.null(desc$URL)) {
    url <- strsplit(desc$URL, "[,[:space:]]+")[[1]][1]
    if (nzchar(url)) return(url)
  }
  paste0("https://cran.r-project.org/package=", pkg)
}

# Build package table
r_files <- list.files(".", "\\.[Rr]$", recursive = TRUE, full.names = TRUE)
pkgs <- unique(unlist(lapply(r_files, get_pkgs)))
ip <- installed.packages()

data.frame(
  Package = c(pkgs, "CmdStan"),
  Version = c(ip[pkgs, "Version"], cmdstanr::cmdstan_version())
) |>
  transform(
    Link = sprintf("<a href=\"%s\" target=\"_blank\">%s</a>",
                   sapply(Package, get_url), Package),
    Desc = sapply(Package, first_sentence)
  ) |>
  (\(d) d[order(tolower(d$Package)), ])() |>
  subset(select = c(Link, Version, Desc)) |>
  setNames(c("Package", "Version", "Description")) |>
  tinytable::tt(escape = FALSE) |>
  tinytable::theme_html(class = "tinytable tinytable-sm")
```
